#!/usr/bin/env python3
"""Generate the minimal browser client directly from FastAPI's OpenAPI document."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPOSITORY_ROOT / "services" / "api"))

# Contract generation never initializes configured cloud integrations.
os.environ["RIGHTSRADAR_MODE"] = "mock"

from app.main import create_app  # noqa: E402

OUTPUT = REPOSITORY_ROOT / "packages" / "api-client" / "src" / "generated.ts"


def to_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", maxsplit=1)[-1]
    if "anyOf" in schema:
        return " | ".join(to_type(item) for item in schema["anyOf"])
    if schema.get("type") == "array":
        item_type = to_type(schema.get("items", {}))
        return f"({item_type})[]" if " | " in item_type else f"{item_type}[]"
    if schema.get("type") == "integer" or schema.get("type") == "number":
        return "number"
    if schema.get("type") == "boolean":
        return "boolean"
    if schema.get("type") == "string":
        return "string"
    if schema.get("type") == "object":
        return "Record<string, unknown>"
    return "unknown"


def render_component(name: str, schema: dict[str, Any]) -> str:
    if "enum" in schema:
        values = " | ".join(json.dumps(value) for value in schema["enum"])
        return f"export type {name} = {values};"
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in properties.items():
        optional = "" if property_name in required else "?"
        lines.append(f"  {property_name}{optional}: {to_type(property_schema)};")
    lines.append("}")
    return "\n".join(lines)


def require_operation(schema: dict[str, Any], path: str, method: str) -> None:
    if method not in schema["paths"].get(path, {}):
        raise RuntimeError(f"OpenAPI operation is missing: {method.upper()} {path}")


def generate() -> str:
    schema = create_app().openapi()
    require_operation(schema, "/api/cases", "post")
    require_operation(schema, "/api/cases/{case_id}", "get")
    require_operation(schema, "/api/cases/{case_id}/findings/{finding_id}", "patch")
    components = schema["components"]["schemas"]
    component_definitions = "\n\n".join(
        render_component(name, component_schema)
        for name, component_schema in sorted(components.items())
    )
    return f'''/* This file is generated by scripts/generate_api_client.py. Do not edit manually. */

{component_definitions}

export type ApiFetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

function apiUrl(baseUrl: string, path: string): string {{
  return `${{baseUrl.replace(/\\/$/, '')}}${{path}}`;
}}

async function request<T>(
  path: string,
  baseUrl: string,
  init: RequestInit,
  fetcher: ApiFetcher
): Promise<T> {{
  const response = await fetcher(apiUrl(baseUrl, path), init);
  if (!response.ok) {{
    throw new Error(`API request failed (${{response.status}})`);
  }}
  return (await response.json()) as T;
}}

export function createCase(
  payload: CreateCaseRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {{
  return request<Case>('/api/cases', baseUrl, {{
    method: 'POST',
    headers: {{ 'Content-Type': 'application/json' }},
    body: JSON.stringify(payload)
  }}, fetcher);
}}

export function getCase(
  caseId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {{
  return request<Case>(`/api/cases/${{caseId}}`, baseUrl, {{ method: 'GET' }}, fetcher);
}}

export function updateFindingStatus(
  caseId: string,
  findingId: string,
  reviewerStatus: ReviewerStatus,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Finding> {{
  return request<Finding>(`/api/cases/${{caseId}}/findings/${{findingId}}`, baseUrl, {{
    method: 'PATCH',
    headers: {{ 'Content-Type': 'application/json' }},
    body: JSON.stringify({{ reviewer_status: reviewerStatus }})
  }}, fetcher);
}}
'''


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generate(), encoding="utf-8")
