/* This file is generated by scripts/generate_api_client.py. Do not edit manually. */

export interface AdvocateReport {
  hypothesis_id: string;
  best_url?: string | null;
  why?: string;
  strength?: string;
  searched_urls?: string[];
}

export interface Asset {
  id: string;
  case_id: string;
  filename: string;
  content_type: string;
  byte_size: number;
  created_at: string;
}

export interface Body_create_case_from_file_api_cases_from_file__production_id__post {
  file: File;
}

export interface Body_upload_asset_api_cases__case_id__assets_post {
  file: File;
}

export interface Body_upload_production_icon_api_productions__production_id__icon_post {
  file: File;
}

export interface Case {
  id: string;
  script_text: string;
  created_at: string;
  findings: Finding[];
  asset_count?: number;
  production_id?: string | null;
  title?: string;
  notes?: string;
  thread?: CaseThreadMessage[];
  tool_calls?: ToolCallEvent[];
}

export interface CaseSummary {
  id: string;
  created_at: string;
  script_excerpt: string;
  finding_count: number;
  asset_count: number;
}

export interface CaseThreadMessage {
  id: string;
  case_id: string;
  author_kind: ThreadAuthorKind;
  body: string;
  agent_name?: string | null;
  member_id?: string | null;
  finding_id?: string | null;
  mentions?: string[];
  created_at: string;
}

export interface ClearanceMemo {
  verdict: MemoVerdict;
  confidence: number;
  winning_hypothesis_id: string;
  dispositive_url?: string | null;
  rationale: string;
  recommended_owner_role: WorkspaceRole;
  hypotheses?: Hypothesis[];
  advocates?: AdvocateReport[];
  assigned_member_id?: string | null;
}

export interface CreateCaseRequest {
  script_text: string;
  production_id?: string | null;
  title?: string;
}

export interface CreateFindingCommentRequest {
  author: string;
  body: string;
}

export interface CreateProductionRequest {
  title: string;
  studio?: string;
  status?: ProductionStatus;
  icon?: string;
  roster?: ProductionMemberInput[];
}

export interface CreateThreadMessageRequest {
  member_id: string;
  body: string;
  finding_id?: string | null;
}

export interface Evidence {
  excerpt: string;
  source: Source;
}

export interface EvidenceSelection {
  primary?: Evidence | null;
  rationale?: string | null;
  alternatives?: Evidence[];
}

export interface Finding {
  id: string;
  case_id: string;
  category: string;
  detected_item: string;
  explanation: string;
  confidence: number;
  supporting_evidence: Evidence[];
  source_urls: string[];
  retrieved_at: string;
  reviewer_status: ReviewerStatus;
  evidence?: EvidenceSelection;
  assignee?: string | null;
  due_date?: string | null;
  comments?: FindingComment[];
  stakeholder_ids?: string[];
  memo?: ClearanceMemo | null;
}

export interface FindingComment {
  id: string;
  author: string;
  body: string;
  created_at: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Hypothesis {
  id: string;
  claim: string;
  likely_rights_holder: string;
  what_would_prove_it: string;
}

export type MemoVerdict = "cleared" | "license_required" | "rewrite_recommended" | "needs_human";

export interface Production {
  id: string;
  title: string;
  studio?: string;
  status?: ProductionStatus;
  icon?: string;
  icon_version?: string | null;
  icon_content_type?: string | null;
  ignore_keywords?: string[];
  roster?: ProductionMember[];
  created_at: string;
}

export interface ProductionMember {
  id: string;
  name: string;
  role: WorkspaceRole;
  email?: string | null;
}

export interface ProductionMemberInput {
  id?: string | null;
  name: string;
  role: WorkspaceRole;
  email?: string | null;
}

export type ProductionStatus = "development" | "pre_production" | "shooting" | "post" | "released";

export interface ProductionSummary {
  id: string;
  title: string;
  studio?: string;
  status?: ProductionStatus;
  icon?: string;
  icon_version?: string | null;
  icon_content_type?: string | null;
  ignore_keywords?: string[];
  roster?: ProductionMember[];
  created_at: string;
  case_count?: number;
  open_finding_count?: number;
  escalated_finding_count?: number;
}

export type ReviewerStatus = "pending" | "accepted" | "dismissed" | "escalated";

export interface Source {
  title: string;
  url: string;
}

export type ThreadAuthorKind = "agent" | "human";

export interface ToolCallEvent {
  id: string;
  case_id: string;
  provider: ToolCallProvider;
  method: string;
  agent_name: string;
  ok: boolean;
  fixture?: boolean;
  summary: string;
  lead?: string | null;
  duration_ms?: number;
  started_at: string;
}

export type ToolCallProvider = "vertex" | "parallel";

export interface UpdateFindingMetaRequest {
  assignee?: string | null;
  due_date?: string | null;
  actor_member_id?: string | null;
}

export interface UpdateFindingRequest {
  reviewer_status: ReviewerStatus;
  actor_member_id?: string | null;
}

export interface UpdateProductionRequest {
  title?: string | null;
  studio?: string | null;
  status?: ProductionStatus | null;
  icon?: string | null;
  ignore_keywords?: string[] | null;
  roster?: ProductionMemberInput[] | null;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export type WorkspaceRole = "production" | "clearance" | "legal";

export type ApiFetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

function apiUrl(baseUrl: string, path: string): string {
  return `${baseUrl.replace(/\/$/, '')}${path}`;
}

async function request<T>(
  path: string,
  baseUrl: string,
  init: RequestInit,
  fetcher: ApiFetcher
): Promise<T> {
  const response = await fetcher(apiUrl(baseUrl, path), init);
  if (!response.ok) {
    throw new Error(`API request failed (${response.status})`);
  }
  if (response.status === 204) {
    return undefined as T;
  }
  const text = await response.text();
  if (!text) {
    return undefined as T;
  }
  return JSON.parse(text) as T;
}

export function createCase(
  payload: CreateCaseRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {
  return request<Case>('/api/cases', baseUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  }, fetcher);
}

export function createCaseFromFile(
  productionId: string,
  file: File,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {
  const body = new FormData();
  body.append('file', file);
  return request<Case>(
    '/api/cases/from-file/' + encodeURIComponent(productionId),
    baseUrl,
    { method: 'POST', body },
    fetcher
  );
}

export function getCase(
  caseId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {
  return request<Case>('/api/cases/' + encodeURIComponent(caseId), baseUrl, { method: 'GET' }, fetcher);
}

export function deleteCase(
  caseId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<void> {
  return request<void>('/api/cases/' + encodeURIComponent(caseId), baseUrl, { method: 'DELETE' }, fetcher);
}

export function listCases(
  limit: number = 10,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<CaseSummary[]> {
  return request<CaseSummary[]>(
    '/api/cases' + '?limit=' + encodeURIComponent(limit),
    baseUrl,
    { method: 'GET' },
    fetcher
  );
}

export function uploadAsset(
  caseId: string,
  file: File,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Asset> {
  const body = new FormData();
  body.append('file', file);
  return request<Asset>(
    '/api/cases/' + encodeURIComponent(caseId) + '/assets',
    baseUrl,
    { method: 'POST', body },
    fetcher
  );
}

export function listAssets(
  caseId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Asset[]> {
  return request<Asset[]>(
    '/api/cases/' + encodeURIComponent(caseId) + '/assets',
    baseUrl,
    { method: 'GET' },
    fetcher
  );
}

export function updateFindingStatus(
  caseId: string,
  findingId: string,
  reviewerStatus: ReviewerStatus,
  baseUrl: string,
  fetcher: ApiFetcher = fetch,
  actorMemberId?: string | null,
): Promise<Finding> {
  return request<Finding>('/api/cases/' + encodeURIComponent(caseId) + '/findings/' + encodeURIComponent(findingId), baseUrl, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ reviewer_status: reviewerStatus, ...(actorMemberId ? { actor_member_id: actorMemberId } : {}) })
  }, fetcher);
}

export function postThreadMessage(
  caseId: string,
  payload: CreateThreadMessageRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {
  return request<Case>('/api/cases/' + encodeURIComponent(caseId) + '/thread', baseUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  }, fetcher);
}

export function createProduction(
  payload: CreateProductionRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Production> {
  return request<Production>('/api/productions', baseUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  }, fetcher);
}

export function listProductions(
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<ProductionSummary[]> {
  return request<ProductionSummary[]>('/api/productions', baseUrl, { method: 'GET' }, fetcher);
}

export function getProduction(
  productionId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<ProductionSummary> {
  return request<ProductionSummary>('/api/productions/' + encodeURIComponent(productionId), baseUrl, { method: 'GET' }, fetcher);
}

export function updateProduction(
  productionId: string,
  payload: UpdateProductionRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Production> {
  return request<Production>('/api/productions/' + encodeURIComponent(productionId), baseUrl, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  }, fetcher);
}

export function deleteProduction(
  productionId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<void> {
  return request<void>('/api/productions/' + encodeURIComponent(productionId), baseUrl, { method: 'DELETE' }, fetcher);
}

export function listProductionCases(
  productionId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case[]> {
  return request<Case[]>('/api/productions/' + encodeURIComponent(productionId) + '/cases', baseUrl, { method: 'GET' }, fetcher);
}

export function uploadProductionIcon(
  productionId: string,
  file: File,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Production> {
  const body = new FormData();
  body.append('file', file);
  return request<Production>(
    '/api/productions/' + encodeURIComponent(productionId) + '/icon',
    baseUrl,
    { method: 'POST', body },
    fetcher
  );
}

export function deleteProductionIcon(
  productionId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Production> {
  return request<Production>('/api/productions/' + encodeURIComponent(productionId) + '/icon', baseUrl, { method: 'DELETE' }, fetcher);
}

export function updateFindingMeta(
  productionId: string,
  caseId: string,
  findingId: string,
  payload: UpdateFindingMetaRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Finding> {
  return request<Finding>('/api/productions/' + encodeURIComponent(productionId) + '/cases/' + encodeURIComponent(caseId) + '/findings/' + encodeURIComponent(findingId) + '/meta', baseUrl, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  }, fetcher);
}

export function addFindingComment(
  productionId: string,
  caseId: string,
  findingId: string,
  payload: CreateFindingCommentRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Finding> {
  return request<Finding>('/api/productions/' + encodeURIComponent(productionId) + '/cases/' + encodeURIComponent(caseId) + '/findings/' + encodeURIComponent(findingId) + '/comments', baseUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  }, fetcher);
}
