/* This file is generated by scripts/generate_api_client.py. Do not edit manually. */

export interface Case {
  id: string;
  script_text: string;
  created_at: string;
  findings: Finding[];
}

export interface CreateCaseRequest {
  script_text: string;
}

export interface Evidence {
  excerpt: string;
  source: Source;
}

export interface Finding {
  id: string;
  case_id: string;
  category: string;
  detected_item: string;
  explanation: string;
  confidence: number;
  supporting_evidence: Evidence[];
  source_urls: string[];
  retrieved_at: string;
  reviewer_status: ReviewerStatus;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ReviewerStatus = "pending" | "accepted" | "dismissed" | "escalated";

export interface Source {
  title: string;
  url: string;
}

export interface UpdateFindingRequest {
  reviewer_status: ReviewerStatus;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export type ApiFetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

function apiUrl(baseUrl: string, path: string): string {
  return `${baseUrl.replace(/\/$/, '')}${path}`;
}

async function request<T>(
  path: string,
  baseUrl: string,
  init: RequestInit,
  fetcher: ApiFetcher
): Promise<T> {
  const response = await fetcher(apiUrl(baseUrl, path), init);
  if (!response.ok) {
    throw new Error(`API request failed (${response.status})`);
  }
  return (await response.json()) as T;
}

export function createCase(
  payload: CreateCaseRequest,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {
  return request<Case>('/api/cases', baseUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  }, fetcher);
}

export function getCase(
  caseId: string,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Case> {
  return request<Case>(`/api/cases/${caseId}`, baseUrl, { method: 'GET' }, fetcher);
}

export function updateFindingStatus(
  caseId: string,
  findingId: string,
  reviewerStatus: ReviewerStatus,
  baseUrl: string,
  fetcher: ApiFetcher = fetch
): Promise<Finding> {
  return request<Finding>(`/api/cases/${caseId}/findings/${findingId}`, baseUrl, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ reviewer_status: reviewerStatus })
  }, fetcher);
}
